global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['172.18.0.1:9113']

  - job_name: 'app'
    static_configs:
      - targets: ['172.18.0.1:80']
    metrics_path: /metrics

  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.0.19  # Proxmox VE node 1
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.71:9221 # PVE address