- name: Install package
  apt:
    name: 
      - docker.io
      - docker-compose
      - htop
    state: present
    update_cache: yes

- name: Make directory
  file:
    path: /opt/app_server
    state: directory

- name: Copy App
  copy:
    src: ../test_app/
    dest: /opt/app_server/test_app/
    mode: preserve

- name: Copy docker-compose.yml
  copy:
    src: ../app_server/docker-compose.yml
    dest: /opt/app_server/docker-compose.yml

- name: Copy nginx.conf
  copy:
    src: ../app_server/nginx.conf
    dest: /opt/app_server/nginx.conf

- name: Up docker-compose
  shell: docker-compose up -d --build
  args:
    chdir: /opt/app_server 